### ISSUE TITLE
item01. 호출될때마다 새로운 객체를 생성하지 않아도 된다는 내용 질문!

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#1]
호출될때마다 새로운 객체를 생성하지 않아도 된다는건, 
1. 그럼 동일한 a객체를 동일한 프로젝트 내에 있는 클래스에서 사용한다는 의미인지,
2. 그렇게 되면 의존성(?)이 커지게 되서 문제가 발생할 수 있지않을까..?
3. 그리고 동일한 객체를 공유하면서 사용할지 , 또는 새로운 객체를 생성하는지에 대한 기준은 프로젝트 마다 달라질수있는지에 대해서 이야기해보고 싶습니다.

**Comment by donghyeon3813** [comment]
종합적으로 이야기 하자면 변동성이 별로 없는 객체에 정적 팩토리 메소드를 적용한다고 생각하면 이해하기가 쉬울 것 같습니다!
값이 변동성이 없기에 굳이 새로운 객체를 만들 필요 없이 메모리에 인스턴스화 되어 있는 객체를 꺼내 사용하면 되니까요.
예시로는 어떠한 설정 값들을 가지고 있는 객체들을 생각해 볼 수도 있겠네요!
