### ISSUE TITLE
item11. Hashcode를 오버라이드 했을때, 실무에서 어떤식으로 사용할수 있는지

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#11]
hashcode를 오버라이드 했을경우에 실무에서 어떤방식으로 사용할수있는지에 대해서 이야기해보고 싶습니다.

**Comment by donghyeon3813** [comment]
제가 생각했을 때는 생성된 객체의 인스턴스가 hash에 관련된 컬렉션에 의해 관리되고 있을 때 인스턴스가 가지고 있는 값들을 비교하여 좀 더 효율적으로 값을 찾기 위해 사용할 수 있어 보입니다.

만약에 hashcode를 재정의하지 않는다면 Object의 hashcode를 사용하게 되고 이는 메모리 주소를 기반으로 hash값을 가져옵니다. 
이 경우에는 아무리 인스턴스가 가지고 있는 값들이 똑같더라도 hash컬렉션에서 값이 저장될 때 다르다고 인식하기 때문에 다른 위치에 저장될 수 있으므로 낭비가 되지 않을까 생각합니다. 

이 밖에 데이터 검색을 제외한 hashcode의 활용에 대해서는 충분히 다른 걸로 대체가 가능하지 않을까 싶습니다.
