### ISSUE TITLE
Item13. 81p 배열의 clone은 런타임 타입과 컴파일타임 타입 모두가 원본 배열과 똑같은 배열을 반환한다.

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#12]
위 말과 Object[] 로 선언된 필드를 직접 clone하였을 때와 Object[] 로 선언된 필드를 가지고 있는 객체를 super.clone 하였을 때 동작이 어떻게 다른지 궁금합니다.

**Comment by polarHub25** [comment]
super.clone의 경우는 object 클래스의 clone() 메소드를 실행하므로 기본적으로 얕은 복사를 수행합니다. 하지만 선언된 필드를 직접 clone() 하는 것은 해당 필드의 정의된clone() 메소드 마다 깊은 복사를 수행할 수도 있습니다.

**Comment by donghyeon3813** [comment]
일반 1차원 배열에서는 깊은 복사가 이루어지며 2차원 배열과 객체 배열은 얕은 복사가 이루어진다고 하는데 이것에 대한 정확한 이유를 토론하고 싶습니다.
