### ISSUE TITLE
item13. 런타임 타입과 컴파일 타임 타입의 차이점

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#14]
2개가 왜 나눠져서(?) 타입이 정의 되는지 그리고 배열은 왜 2개가 같은지에 대해서 토론해보면 좋을거같아요.

**Comment by donghyeon3813** [comment]
자바에서는 공변 반환 타이핑 기능을 지원하기에 컴파일 타입과 런타임 타입으로 나뉘어지는 것 같습니다.
다형성을 사용한 메소드를 사용할 때 컴파일 단계에서는 객체의 부모가 가지고 있는 메소드를 런타임 단계에서는 실제 객체가 가지게 되는 override된 메소드를 사용한다고 하네요(동적 바인딩)

배열은 컴파일 타임에 타입 안정성을 체크하게 구성되어 있어 런타임 타입과 컴파일 타입이 서로 다를 수가 없습니다.
