### ISSUE TITLE
item13. 깊은 복사와 얕은 복사의 차이

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#15]

**Comment by donghyeon3813** [comment]
배열을 예로 들었을 때 얕은 복사는 배열의 값을 참조하고 있는 위치를 복사하는 것입니다 이 때문에 원본 배열의 값이 변경된다면 얕은 복사를 한 배열의 값도 같이 변경되며
깊은 복사는 다른 위치에 기존에 있던 값을 새로 할당하여 원본 배열의 값의 변경에 상관없이 복사했던 값 그대로 유지가 가능합니다.
[깊은 복사, 얕은 복사 예제](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item13/copy.md)
