### ISSUE TITLE
item13. 배열 복사에서 clone과 copy(arraycopy, copyof)의 차이점은 무엇인지

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#16]

**Comment by donghyeon3813** [comment]
clone과, copy(arraycopy, copyof)는 clone은 원하는 만큼의 범위를 지정할 수 없지만 arraycopy는 원하는 범위만큼 배열을 복사할 수 있습니다. 그리고 arraycopy의 경우에는 native 메소드를 사용하여 속도가 더 빠르다고 하지만 실제로 실행해본 결과는 속도는 비슷한 것 같습니다.
[예시 코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item13/ArrayCopy.md)
