### ISSUE TITLE
item15. 99p 클래스에서 public static final 배열 필드를 두거나 이 필드를 반환하는 접근자 메서드를 제공해서는 안된다. 이런 필드나 접근자를 제공한다면 클라이언트에서 그 배열의 내용을 수정할 수 있게 된다.

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#17]
해당 문구에서 클라이언트가 그 배열의 내용을 수정할 수 있게 된다고 나와있는데, 여기서 이야기하는 클라이언트가 어떤건지, 어떤식으로 수정을 할수있는건지 명확하게 이해가 안되서 이슈로 올립니다.

**Comment by donghyeon3813** [comment]
java의 변수에서의 final은 변수의 재할당을 막는다고 합니다. 
배열 같은 경우에는 배열의 주소 값을 변경하는 것이 아닌 참조되어 있는 주소에 들어있는 값을 변경하는 것이므로 final로 선언되어도 배열은 수정이 가능하다고 하네요. 

여기서 말하는 클라이언트는 public static final 배열이 필드나 메서드로 선언되어있는 클래스를 사용하여 코드를 작성하는 사람을 뜻하는 걸로 해석됩니다.
[예시 코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item15/finalArray.md)
