### ISSUE TITLE
item15. 정보 은닉의 장점이 왜 시스템 개발 속도를 높이는 것인지? 

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#19]

**Comment by polarHub25** [comment]
정보 은닉 : 시스템의 상세 구현 내용은 숨기고, 필요한 내용만 외부로 노출하는 개념. (시스템의 복잡성 관리와 모듈간의 결합도를 낮춤 ) 
==> 결합도가 낮아지므로 모듈의 각 부분이 독립적으로 유지되면서, 수정도 용이하게 만들수가 있다고 합니다. 

[예시 코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item15/InformationHiding.md)


EmployeeService 클래스에서 DatabaseManager 클래스의 executeQuery, close 메서드를 통해서만 작업을 수행할수 있으며, 다른 로직은 사용자가 몰라도 됩니다. 또한 DatabaseManager  내부의 객체의 구현이나 라이브러리가 변경되어도 EmployeeService  클래스에는 영향을 주지 않는다는것. 즉 결합도가 낮다고 볼수가 있습니다.
