### ISSUE TITLE
item03. 싱글턴 클래스의 역직렬화 관련 질문!

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#2]
1. 싱글턴 클래스를 직렬화하고 역직렬화할 때마다 새로운 인스턴스가 만들어지는 이유가 궁금해요!
2. readResolve 메서드를 추가한 것만으로 역직렬화시에 원래의 인스턴스가 반환되는 이유에 대해서 이야기하고 싶습니다.

**Comment by polarHub25** [comment]
1. 자바의 역직렬화 자체가 생성자로서의 역할을 수행하므로, 인스턴스를 또다시 만들기 때문에 직렬화에 사용한 인스턴스와는 전혀 다른 인스턴스가 된다고 합니다. 
2. readResolve 메소드는 역직렬화 과정에서 반환되는 인스턴스를 원하는 것으로 바꿀수 있다고 함!
-> 테스트 코드가 필요할거같은.. 
https://github.com/Java-Bom/ReadingRecord/issues/4 비슷한 이슈인거같은데 여기 코드 보고 토론 고고!
