### ISSUE TITLE
item15. serializable을 구현한 클래스는 그 필드들이 의도치않게 왜 공개 api가 되는가? 

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#20]
98p 왜 그런지 토론해보면 좋을 것 같습니다.

**Comment by donghyeon3813** [comment]
Serializable를 구현하게되면 직렬화와 역직렬화를 통하여 필드들을 외부에서 직접 접근을 할 수 있게 되어 공개 api가 된다고 하는데.. 음 좀 더 이야기 해보면 좋을 것 같습니다!

**Comment by polarHub25** [comment]
[예시코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item15/SerializableApi.md)

name, age 는 private 필드로 외부에서 직접적으로 접근이 안되지만,Serializable로 구현하게 되면 필드 데이터가 직렬화 데이터 포맷의 일부가 됨. 
=> 클래스의 인스턴스가 직렬화될때, 해당 인스턴스의 모든 필드는 바이트로 변환이 된다고 합니다. 그래서 이때 바이트 정보에는 필드의 데이터 타입, 필드 값 등이 포함되서 공개 api로 외부에 노출이 될수 있습니다.
