### ISSUE TITLE
item18. 114페이지 메소드 호출과 달리 상속은 캡슐화를 깨뜨린다.

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#23]
상속이 캡슐화를 깨뜨린다는 의미가 상속받은 하위 클래스의 기능에 대해서 고유성(?)을 깨지게 한다는 의미인지 또는 다른 의미인지에 대해서 궁금합니다.

**Comment by donghyeon3813** [comment]
캡슐화는 클래스의 필드나 메서드의 외부로부터의 접근을 제한하는 것입니다.
만약에 부모 클래스에서 필드의 값을 반환하는 메서드를 자식 클래스에서 오버라이딩하여 부모 클래스에서 의도한 대로 동작하지 않는 새로운 동작을 제공한다면 이는 부모 클래스에서 필드의 값을 반환한다는 의도를 망가트리는 것이므로 캡슐화가 깨진 것이라고 이해할 수 있을 것 같아요.
