### ISSUE TITLE
item18. 121p 래퍼 클래스는 하위클래스보다 견고하고 강력하다. 

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#24]
위 문장의 의미에 대해서 이해가 안되서 이슈로 올립니다 !

**Comment by donghyeon3813** [comment]
래퍼 클래스와 컴포지션을 활용하여 상속을 했을 때의 취약 점들을 보완할 수 있으며, 이점도 많다는 것을 함축적인 의미로 표현하고 있네요 
제가 이해한 컴포지션의 장점은 이렇습니다.
1. 기능을 확장하거나 변경이 필요하다면 기존 클래스에 변경하는 것이 아닌 래퍼 클래스에 새로운 기능을 추가하거나 변경할 수 있다.
2. 상속 자체는 캡슐화가 깨질 수도 있지만 컴포지션을 사용한다면 캡슐화를 유지할 수 있다.
