### ISSUE TITLE
item19. 123p . 효율적인 하위 클래스를 큰 어려움 없이 만들수 있게 하려면 클래스의 내부 동작 과정 중간에 끼어들수 있는 훅(hook)을 잘 선별하여 protected 메서드 형태로 공개해야 할수도 있다

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#25]
- public, default 상태로 재정의를 할수있는데 왜 protected로 공개해야 하는걸까요? 
- 훅 메소드 라는건 재정의 가능한 메소드를 말하는걸까요? 그렇다면 훅 메소드 라는 정의는 디자인 패턴의 용어로 이해하면 되는지 이야기 해보고싶습니다.

**Comment by donghyeon3813** [comment]
public은 모든 클래스에서 접근이 가능하여 너무 범위가 넓고 default를 사용하게 되면 상속관계에서는 재정의를 할 수 없으므로 protected 형태로 제공을 하려는 것으로 보입니다.

hook의 경우에는 하위 클래스에 따라 내부동작을 다르게 할 수 있는 메서드를 뜻합니다.
대표적인 예시로 템플릿 메소드 패턴에서 hook 메소드를 활용하고 있습니다
