### ISSUE TITLE
item24. 중첩 클래스 종류

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#28]
중첩 클래스 종류에 대해서 책에 예시가 없고, 내용 자체가 크게 와닿지 않아서 다음 스터디때 각자 이해한 내용에 대해서 자세히 스터디 했으면 합니다..! 그리고 관련된 이슈사항이나 정리된 내용이 있다면 하위에 달아주세요!

**Comment by donghyeon3813** [comment]
각 중첩 클래스의 종류별로 특징을 볼 수 있는 예시를 정리해보았습니다.
[코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item24/nestedClass.md)

**Comment by polarHub25** [comment]
추가적으로 각각의 중첩 클래스의 사용 이유에 대해서 추가적으로 스터디 하기!

**Comment by donghyeon3813** [comment]
1. 정적 멤버 클래스 : 비정적 멤버 클래스를 사용할 경우에 강한 참조가 일어나 gc 대상에서 제외 될 수 있기 때문에 사용
2. 비정적 멤버 클래스 : 외부 클래스와 관련된 작업을 수행하게 될 때 사용
3. 지역 클래스 :  사용된 메서드의 보조적인 역할의 클래스가 필요한 경우와 메서드 내부에서 생성되기 때문에 자연스레 캡슐화가 이루어지기 때문에 사용
4. 익명 클래스 : 하나의 메서드를 재정의하여 일회용으로 사용하여야 할 때 사용
