### ISSUE TITLE
item22. 140p 바이너리 호환성을 위해 여전히 상수 인터페이스를 구현하고 있어야 한다.

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#29]
바이너리 호환성이란 무엇을 뜻하고 어떠한 이유에서 상수 인터페이스를 구현하고 있어야 한다고 하는 것일까요?

**Comment by polarHub25** [comment]
**바이너리 호환성**이란 소프트웨어 시스템에서 컴파일된 바이너리 파일( 실행 파일 , 라이브러리)이 코드를 변경하지 않고도 동일하게 실행될 수 있는 능력이라고 합니다. 실행되는 원리로는, 컴파일된 바이너리 파일에는 함수, 변수, 클래스 등은 각각의 주소에 매핑되어 저장이 되어있는데 이때 코드가 변경되지 않는다면, 정상적으로 바이너리 호환성이 가능하다고 합니다. 그렇기 때문에 다음 릴리스에서 구현된 상수 인터페이스를 사용하지 않아도 정상 동작을 위해 여전히 상수인터페이스를 구현하고 있어야 한다는 의미인거같습니다.

**Comment by polarHub25** [comment]
[ 2024.07.03.수 스터디 이후 추가된 궁금점 ]
1. 자바에서 컴파일이 되는 과정( 기존코드에 컴파일된 코드를 가지고 있다가 수정된 사항과 비교를 하게 되는건지 )
2. .class 파일이 생성되는 기준 ( build 폴더가 프로젝트마다 생성여부가 다르던데 왜그런지에 대한 이슈 )
