### ISSUE TITLE
item02.빌더

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#3]
19p. 빌더 패턴은 계층적으로 설계된 클래스와 함께 쓰기에 좋다고 나와있는데, 
추상 클래스에 빌더를 선언해 놓으면, 하위 클래스가 그 빌더를 오버라이딩 해서 사용할 수 있으므로 쓰기 좋다는 의미가 맞는지..?

**Comment by donghyeon3813** [comment]
제 생각하는 좀 더 구체적인 이유는 아래와 같습니다.
1. 빌더를 오버라이드하여 공변 반환 타이핑 기능을 사용하여 형 변환을 신경 쓰지 않아도 된다.
2. 하위 클래스에서 필요에 따라 빌더에 특성을 추가할 수 있다.
3. 메서드 연쇄 기능을 지원하기 쉽다.
