### ISSUE TITLE
item26. 비한정적 와일드 카드의 사용 용도

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#30]
비한정적 와일드 카드를 사용한 list에는 null밖에 넣을 수 없다고 합니다.
그렇다면 왜 사용하는지? 어느 상황에 이것이 필요한지에 대해서 알면 좋을 것 같습니다.

**Comment by polarHub25** [comment]
[ 2024.07.03 스터디 이후 추가된 이슈 ]
1. 비한정적 와일드 카드랑 제네릭 타입의 차이점은 무엇인지

**Comment by donghyeon3813** [comment]
비한정적 와일드 카드 : 타입을 전혀 신경 쓰지 않겠다. 
제네릭 타입 : 타입이 정해지면 그 타입에 맞게 관련된 기능은 사용할 수 있다.

비한정적 와일드 카드는 타입을 전혀 신경 쓰지 않으므로 List에 add method를 사용할 때 어떠한 데이터가 들어올지 알 수 없으므로 컴파일 단계에서 null을 제외하고는 입력할 수 없습니다. 

[코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item26/Generic.md)
