### ISSUE TITLE
item28. 제네릭타입이 런타임에 타입소거가 일어나는 이유에 대해서

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#31]
이유에 대해서 스터디 해봅시다.

**Comment by polarHub25** [comment]
1. 이전 java 5 버전과의 호환성 ( 기존의 비제네릭 코드와 제네릭 코드가 함께 사용되게 하기 위해서 )
2. 컴파일 단계에서 타입 검사를 완료함으로써 런타임 단계에서 추가적인 검사를 줄임으로써 런타임 단계의 성능 향상
