### ISSUE TITLE
item31. PECS에서 extends와 super의 차이점에 대해서 

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#32]

**Comment by donghyeon3813** [comment]
List를 통해 예시를 들어보겠습니다.
`List<? extends Number> numbersExtend`
`List<? super Integer> integerSuper`

1.`numbersExtend`의 경우에는 `Number`를 부모로둔 어떠한 타입의 리스트를 선언할 수 있습니다.
이 경우 `Number`를 상속한 경우  `Number, Integer, Double, Float` 등의 데이터가 있습니다. 
`Number`를 상속했지만 엄연히 `List<Number>`와 `List<Integer>`는 하위 타입이 아니며 정확한 타입을 알 수 없어 컴파일러가 add 함수의 사용을 못하게 막습니다. 
2. `integerSuper`의 경우에는 `Integer`를 하위 타입으로 둔 어떠한 타입의 리스트를 선언할 수 있습니다.
이 경우 `Integer, Number, Object`등 어떠한 타입이 올지 특정 되기 때문에 컴파일러가 add 함수의 사용을 가능하게 합니다.

[코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item31/FecsEx.md)
