### ISSUE TITLE
item.30 항등 함수를 담은 클래스를 사용하는 이유

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#33]
177p 항등 함수를 담은 클래스를 사용하는 이유와 실제로 어떤식으로 사용할 수 있는 지에 대해서 공부해봅시다.

**Comment by polarHub25** [comment]
항등 함수를 사용하는 이유
=>  변환이 필요없는 경우에 기본값으로 사용, 조건에 따른 변환, 타입 안정성, 코드 재사용 등 코드의 일관성과 유연성을 위해 사용

[참고 코드 (코드로 보면 더 이해가 잘됩니다) ](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item30/Identity.java)

**Comment by donghyeon3813** [comment]
실제로 사용되는 사례들 중에 stream 사용 시에 사용되는 groupBy도 항등 함수의 좋은 예시인 것 같아 올립니다.
[코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item30/Identity2.md)
