### ISSUE TITLE
item.34 static final의 사용처

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#34]
enum이 넓은 면에서 static final보다 장점이 많다고 합니다.
그렇다면 어떤 부분에서 static final을 사용하였을 때 enum을 사용했을 때보다 더 좋은 효과를 가져올까요?

**Comment by polarHub25** [comment]
enum 은 타입 안전성과 상수의 그룹화를 관리하기 위해 주로 사용되므로 static final을 사용하는 경우가 더 효율적인 경우는 단순한 상수 값을 정의하는 경우에는 static final이 적합할 수 있다고 생각합니다.
