### ISSUE TITLE
item34.필요한 원소를 컴파일 타임에 다 알수있는 상수 집합이란? (219페이지)

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#35]
우선 "필요한 원소를 컴파일 타임에 다 알 수 있는 상수 집합이란" 말이 명확하게 이해가 되지않았고, 이야기를 하다보니, static final과 열거타입은 사용법은 유사한데, 특정 상수값을 여러 클래스에서 가져다 쓸때 열거타입을 써야한다고 이야기가 나왔습니다. 
--> 그렇다면 static final 과 enum class의 컴파일 범위는 다른건가요?

**Comment by donghyeon3813** [comment]
static final의 경우에는 바이너리 호환성에 대해서 공부하였듯이 여러 파일에서 해당 필드를 사용 중이고 값의 변경이 이루어졌다면 파일마다 컴파일이 이루어져야 변경된 값이 옳게 적용이 되지만 enum의 경우에는 일반 class와 같이 객체 참조를 통해서 값을 가져오는 것이기 때문에 값의 변경사항이 있다면 enum class만 컴파일이 이루어져도 변경된 값을 옳게 가져올 수 있습니다.
