### ISSUE TITLE
item02. "빌더를 이용하면 가변인수 매개변수를 여러개 사용할 수 있다" 이 말에서 빌더와 가변인수의 관계란?  

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#4]
책 21p 참고..!

**Comment by donghyeon3813** [comment]
가변인수는 각각의 메서드와 생성자에 딱 한 번만 선언이 가능합니다.
그런데 이를 빌더 패턴의 특징인 메서드 연쇄를 활용하게 되면 가변인수로 선언된 메서드를 여러번 호출하여 객체를 생성할 수 있습니다.

[Builder Code 참조](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item02/BuilderEx.md)

만약 생성자 방식을 사용하여 객체를 만든다고 하면 매우 번거로운 과정이 될 것 같습니다.
