### ISSUE TITLE
item45. Stream 동작원리

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#40]
스트림의 중간연산과 종단 연산의 차이점과 
스트림의 동작원리중 지연평가의 개념에 대해서 깊게 습득해서 토론해보아요

**Comment by donghyeon3813** [comment]
중간연산: 중간 연산은 스트림을 변환하거나 필터링하는 작업을 수행하지만, 이 자체로는 스트림의 요소들을 소비하지 않으며 중간 연산은 결과적으로 또 다른 스트림을 반환한다.

종단연산: 종단 연산은 스트림의 처리 파이프라인을 마무리하고, 스트림의 요소들을 소비하며 최종 결과를 반환하거나 특정 동작을 수행한다.

지연평가: 스트림의 종단연산이 실행되기전까지는 중간연산들을 실행하지 않으며 종단연산에 필요한 만큼 중간 연산들을 실행한다. ex) findFirst 요소가 최초 1건만 필요하여 1건만 연산을 수행
추가로 스트림의 연산은 1건씩 순회하며 처리됨
