### ISSUE TITLE
item. 63 문자열에 사용되는 +연산자와 StringBuilder

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#43]
둘의 어떠한 차이로 인해 성능의 차이가 발생하는 지에 대해서 알아보았으면 합니다.

**Comment by polarHub25** [comment]
불변성과 가변성의 차이로 인한 성능차이 
한두번의 결합에서는 크게 문제가 되지 않지만, 
"+" 연산자의 경우 불변성 객체로, 반복문이나 다수의 문자열 결합시에는 새로운 객체를 생성하므로 성능이 가변성 개체보다 좋지 않음 
StringBuilder는 가변성 객체로 객체를 생성한 이후에도 새로운 객체를 생성하지않고, 미리 할당된 공간에 문자열을 추가할 수 있으므로 불변성 객체보다 성능이 좋음
