### ISSUE TITLE
426 페이지에 락 분할과 락 스트라이핑의 차이점과 실무에서 접할수 있는 상황에 대해서 토론

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#45]

**Comment by polarHub25** [comment]
- 락 분할 : 서로 다른 객체나 리소스에 대한 락을 분리하여 사용하는 방식 
- ex) 사용자 정보, 제품 정보가 각각의 캐시로 관리되는 경우, 각 캐시에 별도의 락을 걸어 동시에 접근(데이터 변경 등 )할 수 있게 하는것. ( 개별적인 락을 적용해 동시성 높이는 방식. 즉 데이터의 일관성 보장 ) 
- 락 스트라이핑 : 동일한 객체나 리소스 내부에서 여러개의 락을 분산해 사용하는 방식. 
- ex) 하나의 큰 해시 테이블에 여러 버킷이 존재할 수 있는데, 각 버킷에 개별적인 락을 적용하여 여러 스레드가 해당 객체에 동시에 접근할 수 있게 함으로써 성능 최적화 방식

**Comment by donghyeon3813** [comment]
락 분할 : 객체안에 기능별로 락을 따로 두어서 동일한 기능에 대해서는 동시 호출을 제한하지만 독립된 기능은 동시에 호출 가능하게끔하는 방식
