### ISSUE TITLE
item.85 직렬화와 json

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#46]
일반 API 호출시에 직렬화 처리과정과 json으로 처리했을 때의 과정 이 둘의 차이점

직렬화 대신에 json과 프로토콜버퍼를 사용해야되는 이유와 이점들이 무엇이 있는지 추가로 확인

**Comment by polarHub25** [comment]
| 구분               | **일반 직렬화**                                                                                                     | **JSON 직렬화**                                                                                   |
|--------------------|-------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| **직렬화 과정**    | 1. 객체를 `ObjectOutputStream`을 사용해 바이너리 데이터로 변환<br>2. 바이너리 데이터를 네트워크로 전송<br>3. 서버에서 `ObjectInputStream`으로 역직렬화하여 객체 복원 | 1. 객체를 JSON 문자열로 변환 (`ObjectMapper.writeValueAsString`)<br>2. JSON 데이터를 네트워크로 전송<br>3. 서버에서 JSON 파싱 후 객체로 복원 |
| **장점**           | - 데이터 크기가 작아 전송 속도가 빠름<br>- 복잡한 데이터 구조를 처리하기 용이                                       | - 언어/플랫폼 독립적<br>- 사람이 읽고 쓰기 쉬워 디버깅이 용이<br>|
| **단점**           | - Java 외 다른 언어와의 호환성 부족<br>- 클래스 버전 불일치 시 역직렬화 오류 발생 가능                               | - 데이터 크기가 큼<br>- 텍스트 파싱 과정에서 바이너리 직렬화보다 성능이 다소 떨어질 수 있음          |
