### ISSUE TITLE
 item06. "유한 상태 머신을 만들기 떄문에 인스턴스 생성 비용이 높다."

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#5]
32p 에서 말하는 유한 상태 머신이 정확히 무엇인지 이걸로 인해 왜 인스턴스 생성 비용이 높은 지에 대해 궁금합니다.

**Comment by polarHub25** [comment]
인스턴스 생성 비용이 높다는것은 메모리 사용량 또는 리소스가 많이 사용된다는 의미인데, 대체 유한 상태 머신은 정확히 무슨 의미인지 이해가 가지않습니다.

**Comment by polarHub25** [comment]
제가 정리해본 유한상태머신(FSM) 
- 단순히 다른 함수를 호출해서 처리하는 로직이 아닌, FSM은 상태(State), 이벤트(Event), 전환(Transition), 액션(Action) 같은 요소들로 구성이 되어있어야한다. 

1. 상태 : 특정 조건이나 상황 
2. 이벤트 : 상태를 전환
3. 전환 : 다른 상태로의 이동 
4. 액션 : 전환이 발생했을때, 특정 함수를 호출하거나 데이터 변경 작업

-->  시스템의 상태가 명확하게 정의되고, 이벤트에 따라 상태 전환을 관리되며, 상태전환이 발생할때, 각 상태에서 가능한 액션이 정의된 것이 FSM의 동작방식

[예시 참조](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item06/FsmExample.md)
