### ISSUE TITLE
item06. 객체 풀

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#6]
34p 에서 말하는 객체 풀이란? 무엇을 말하는 것인지 궁금합니다.

**Comment by polarHub25** [comment]
" 단순히 객체 생성을 피하고 자 여러분만의 객체 풀을 만들지는 말자" 라는 말의 의미에 대해 궁금하신건가요?

**Comment by donghyeon3813** [comment]
넵 맞습니다.

**Comment by polarHub25** [comment]
우선 객체 풀의 개념은 미리 초기화된 객체의 집합을 보관하는 컨테이너이고, 필요할 때 객체를 풀에 가져와 사용하고, 사용이 끝나면 풀에 반환 -> 객체를 생성하고, 소멸시키는 비용을 줄일수 있음.

객체 풀 생성의 좋은 예시 : 데이터베이스 연결 (리소스가 큼) , Thread pool, Buffer pool

객체 풀 생성이 권장되지않는 예시 : http 
이유 : 서버에서는 http 요청 자체는 객체를 재사용하는 것이 아니라, 요청을 처리만 하고, 요청마다 처리될때 스레드 풀 같은 다른 자원기법의 사용이 가능합니다.  그리고 서버에서는 클라이언트와의 연결을 http객체 풀 생성이 아닌, 내부적인 웹 서버 등이 이를 처리해 줄수 있습니다. 

즉, 객체 풀 생성시에는 해당 객체 풀의 필요성과 비용, 문제점 등을 고려해서 만들자 라는 의미인거같습니다..!
