### ISSUE TITLE
item07. 리스너 혹은 콜백

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#7]
39p 에서 말하는 리스너 혹은 콜백이 왜 메모리 누수의 주범인지, "뭔가 조치해주지 않는 한 콜백은 계속 쌓여갈 것이다" 라는 말의 의미에 대해서 알려주세요

**Comment by polarHub25** [comment]
리스너 예시 정리해서 올려볼게요

**Comment by polarHub25** [comment]
리스너와 콜백이 메모리 누수의 주범이 되는 경우에는, 리스너와 콜백이 등록된 객체를 오랫동안 참조하게 되면서, 가비지 컬렉터가 이러한 객체를 정리하지 못해서 주범이 될수가 있다고 합니다. 

예시 코드에 보면 EventSource 클래스가 EventListener 인터페이스를 구현하는 리스너들을 관리합니다. EventSource의 registerListener 메소드를 통해 리스너를 등록할 수 있고, notifyListeners 메소드는 등록된 모든 리스너들에게 이벤트 발생을 알립니다.
notifyListeners 메소드 내에서는 간단한 for 반복문을 사용하여 listeners 리스트에 있는 각 EventListener 객체의 onEvent 메소드를 호출합니다. 이때 EventSource 클래스에서 리스너 등록 해제 메소드가 존재하지 않으므로, 메모리 누수가 발생할수있습니다.

[예시코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item07/MemoryLeakEx.md)
