### ISSUE TITLE
item07. 강한 참조와 약한 참조의 차이에 대해 명확하게 토론해보고싶습니다. 

### ISSUE THREAD

**Issue by polarHub25** [polarHub25/StudyLog#8]
이론은 이해가 어느정도 갔는데, 테스트 코드를 다시 만들어봐야할거같습니다.

**Comment by donghyeon3813** [comment]
[테스트 코드](https://github.com/polarHub25/StudyLog/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/item07/ReferenceEx.md) 올렸습니다!
