### ISSUE TITLE
item10. "필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다."

### ISSUE THREAD

**Issue by donghyeon3813** [polarHub25/StudyLog#9]
63p에 비교하기가 아주 복잡한 필드의 경우 "필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다." 이 말이 이해가 가질 않습니다. 
예시를 보여주세요.

**Comment by polarHub25** [comment]
비교 연산이 빈번하게 발생되는 경우에 요구되는 필드의 값을 미리 처리하여 저장해 두고, 그 처리된 형태(표준형)으로 비교를 수행함으로써 효율이 높아진다 라는 의미로 이해하면 될거같습니다. 예시 코드를 보면 , 
~~~ java 
public class CaseInsensitiveString implements Comparable<CaseInsensitiveString> {
    private final String originalString;
    private final String normalizedString; // 소문자로 변환된 문자열을 저장

    public CaseInsensitiveString(String originalString) {
        this.originalString = originalString;
        this.normalizedString = originalString.toLowerCase(); // 생성 시점에 소문자로 변환하여 저장
    }

    // 비교
    @Override
    public int compareTo(CaseInsensitiveString o) {
        return this.normalizedString.compareTo(o.normalizedString); // 저장된 소문자 문자열을 사용하여 비교
    }
}

~~~~

추가적으로 제가 이 질문에 대해서 답을 하면서 생긴 궁금증이, 호출 할때마다 객체를 변환하는거랑 생성 시점에 객체를 변환해서 비교하는거랑 차이가 명확히 이해가 안갔는데,만약 동일한 객체의 비교를 자주 수행하는 경우 매번 변환을 거쳐야 하는데 미리 변환한 표준형값으로 가지고 있을 경우에는 반복적으로 변환하는 비용을 절약할 수 있다고 합니다..!
